### ISSUE TITLE
MacOS Update Needed for Blender 2.93.6 Please!

### ISSUE THREAD

**Issue by artcore-c** [Unity-Technologies/MeshSyncDCCPlugin#140] opened 2021-11-21 23:12 UTC
.zip files included are only up archived Blender release 2.93.4 which installs but cannot be activated? 
Try to check box and get py script error no module found no module named MeshSyncClientBlender

**Comment by sindharta** [comment] 2021-11-22 09:34
Thank you for the report. We'll take a look at this as soon as possible.

**Comment by seandillon92** [comment] 2022-01-14 12:19
@artcore-c I have the same issue, I managed to solve it by renaming the imported .so file of the plugin in this location /Users/<user>/Library/Application Support/Blender/2.93/scripts/addons/MeshSyncClientBlender/ 
from MeshSyncClientBlender.cpython-39m-darwin.so to MeshSyncClientBlender.cpython-39-darwin.so

While it worked for me, it looks like bad practice so it might be better to wait for the fixed version

**Comment by sindharta** [comment] 2022-01-18 03:01
@seandillon92 Thank you for finding out the cause of the problem.

And I'd like to apologize for being late in fixing this. MeshSyncDCCPlugins is a subset of tools that we are developing, and our priority has been in another area these days.
That said, I estimate that I'll be able to release a fix next week.

**Comment by sindharta** [comment] 2022-01-28 05:28
This issue has been fixed in the latest [MeshSyncDCCPlugins@0.10.1-preview](https://github.com/Unity-Technologies/MeshSyncDCCPlugins/releases/tag/0.10.1-preview) release.
Please use the auto-installation on the MeshSync's Preferences page, or install the plugin manually.

**Comment by sindharta** [comment] 2022-02-25 07:05
Closed due to non-activity.
Please feel free to reopen if the issue persists.

**Closed as completed by sindharta** 2022-02-25 07:05 UTC
