### ISSUE TITLE
Why supports only Standalone Build?

### ISSUE THREAD

**Issue by wewrere41** [Unity-Technologies/MeshSyncDCCPlugin#226] opened 2022-07-18 15:58 UTC
We are developing android games. And we would like to use mesh sync. Will Android build support come?

**Comment by sindharta** [comment] 2022-07-19 02:22
For runtime builds in Android ?
It's not in our roadmap for now.

FYI, this is a duplicate of 
https://github.com/unity3d-jp/MeshSync/issues/110

**Comment by wewrere41** [comment] 2022-07-19 07:00
> For runtime builds in Android ? It's not in our roadmap for now.
> 
> FYI, this is a duplicate of [unity3d-jp/MeshSync#110](https://github.com/unity3d-jp/MeshSync/issues/110)

No runtime. I mean target build platform . Its can't works when I change target platform to android.

**Closed as completed** 2022-07-19 07:21 UTC
