### ISSUE TITLE
Blender Crash on AutoSync or ManualSync

### ISSUE THREAD

**Issue by Labelpastek** [Unity-Technologies/MeshSyncDCCPlugin#98] opened 2021-03-19 20:48 UTC
When I click on autoSync or Manual sync blender crash immediately.
The mesh sync server works, I checked with this address : http://127.0.0.1:8080/
I don't have any error in unity console.

I tried with different version:
-  MeshSync (0.7.1 or 0.6.1)
- Blender 2.9.0 / 2.9.1 / 2.91.0
- Unity 2019 LTS / 2020.3 LTS

I test with my current project, and also new project.
![dsfgd](https://user-images.githubusercontent.com/33765612/111840408-a5d0e900-88fc-11eb-9260-8010a1af30ab.gif)

**Comment by sindharta** [comment] 2021-03-20 03:53
I did a brief test, but unfortunately I couldn't reproduce it.
I used:

1. Unity 2019.4.22
2. MeshSync 0.7.1-preview
3. Blender 2.91.0

![meshsync](https://user-images.githubusercontent.com/7379311/111858294-2b937980-897b-11eb-96fc-74970349faea.gif)

Anything else that you can share ?
Or is it possible for you to try it on a different machine ?

**Comment by Labelpastek** [comment] 2021-03-20 14:17
Okay I really don't understand what happens.

1. I use exactly the same version than you for Unity, MeshSync and Blender but it still crashes.
2. I thought it was because I use Unity URP in my current project but that doesn't change anything.
3. I also tried to "clean" Blender avoiding to import all custom ad-dons from previous version but it doesn't work.

![image](https://user-images.githubusercontent.com/33765612/111872926-3c011f80-898e-11eb-87dd-51189d16d679.png)

I tried to launch blender from command prompt. When I tried to AutoSync but there is no server in Unity, the message "MeshSync: server is not working" appeared. But when I click on AutoSync with Server in Unity, Blender quit and I just have the last command line (blender directory path).

Sorry I can't test on another computer but I can send you my computer setup, could it help you?

[EDIT]
I also tried with blender 2.83 LTS same issue and I updated windows.
When I install MeshSync Package, I have to add the "MeshSyncDCCPlugins~" folder manually in my Asset folder. Actually this folder is not added automatically (for MeshSync 7.1 not sure for other version). Could be a problem?

**Comment by sindharta** [comment] 2021-03-22 02:26
> When I install MeshSync Package, I have to add the "MeshSyncDCCPlugins~" folder manually in my Asset folder. Actually this folder is not added automatically (for MeshSync 7.1 not sure for other version). Could be a problem?

Thank you for letting me know of this problem. I will fix the above

Just to clarify, can you please attach your MeshSync preference page that shows the version, and the MeshSync tab in Blender that shows the plugin Version ?

![image](https://user-images.githubusercontent.com/7379311/111932645-337d2600-8b01-11eb-84fb-4c12e5fb3789.png)

And, would it be possible for you to get Blender crash logs ?
https://docs.blender.org/manual/en/latest/troubleshooting/crash.html

**Comment by Labelpastek** [comment] 2021-03-22 15:30
Yes sure!

![image](https://user-images.githubusercontent.com/33765612/112010593-bc0ebd00-8b27-11eb-8b31-9a7644f90222.png)
![image](https://user-images.githubusercontent.com/33765612/112010670-d052ba00-8b27-11eb-91fb-f5cead0075d8.png)

That's the weird thing... I don't have any crash log from blender. I tried using command prompt and this function:

![image](https://user-images.githubusercontent.com/33765612/112014458-3260ee80-8b2b-11eb-8e45-670fd3b8e1ec.png)
![image](https://user-images.githubusercontent.com/33765612/112014400-22490f00-8b2b-11eb-8fe2-5009612b3f82.png)

There is only the event when I click on "AutoSync" and just the last line appears when blender crashes.
It looks like blender quit normally.

**Comment by sindharta** [comment] 2021-03-23 09:34
> When I install MeshSync Package, I have to add the "MeshSyncDCCPlugins~" folder manually in my Asset folder. Actually this folder is not added automatically (for MeshSync 7.1 not sure for other version). Could be a problem?

This has been fixed in com.unity.meshsync@0.7.2-preview

For your Blender crash problem, I am not sure how I can help. 

Maybe try booting windows in safe mode, or disabling firewall/antivirus that you may have temporarily ?
Or create a new user in your Windows and try the same thing with the new user ?

A more bold approach would be to create a separate partition on your hard drive and install a clean Windows there to see if you can reproduce the error.
Unfortunately, it seems that Blender can't run on a virtual machine (Hyper-V).

**Comment by Labelpastek** [comment] 2021-03-23 14:51
> This has been fixed in com.unity.meshsync@0.7.2-preview
Perfect it works!

![dsfgd](https://user-images.githubusercontent.com/33765612/112165136-c21ba100-8bee-11eb-8935-fad7d5de78f5.gif)

Not sure that can help you, but if I disable all sync parameters blender doesn't crash but if I try to enable one parameter, it automatically crashes. I think I'm going to reset my Windows and test it again.

Thanks for helping I will post a new comment if I find anything about this issue!

**Comment by sindharta** [comment] 2021-03-24 01:00
Please keep us posted.

**Comment by Labelpastek** [comment] 2021-04-07 20:39
Hello!

I made a test on another computer and it works. Just a question, I made a simple animation to test and when animation is playing in blender, the animation render is not really smooth in unity. Is it normal? Is it necessary to configure the mesh sync to improve framerate?

![trfese](https://user-images.githubusercontent.com/33765612/113930786-04013580-97f2-11eb-8405-92ad659af267.gif)

Thanks for helping.

**Comment by sindharta** [comment] 2021-04-09 08:04
> I made a test on another computer and it works. 

That is great to hear.

> Is it normal? Is it necessary to configure the mesh sync to improve framerate?
That is normal. When "Auto Sync" is on, the plugin will sync the data periodically to Unity, but it's going to be a lot less than 33 times per second to prevent network clog.

To view the animations in Unity, we can press the "Sync" button under Animation section to send the Animation data to Unity, and after this Animation sync is finished, then we can press the play button in Unity to view the animations.

![image](https://user-images.githubusercontent.com/7379311/114148750-13e55a80-9955-11eb-9717-fba09b1a7956.png)

**Comment by Labelpastek** [comment] 2021-04-09 08:53
Okay, thanks for helping!
Everything works perfectly (install package, sync with blender, animation).

**Comment by sindharta** [comment] 2021-04-09 13:29
Please keep us updated on the cool stuffs that you are making with MeshSync :D

**Closed as completed by sindharta** 2021-04-09 13:29 UTC
